### ISSUE TITLE
There is a error when attach application

### ISSUE THREAD

**Issue by firekeeper123** [federicodotta/Brida#62] opened 2020-08-14 10:14 UTC
Pyro server started correctly  
Exception with attach application net.razorvine.pyro.PyroException: [builtins.ValueError] invalid literal for int() with base 10: 'com.example.test'
net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender$17.run(BurpExtender.java:2713) java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) java.base/java.lang.Thread.run(Thread.java:832)

**Comment by gu0o00** [comment] 2021-03-11 02:01
@federicodotta 这个问题你解决了吗，是怎么解决的？

**Comment by federicodotta** [comment] 2021-03-11 08:03
Hi @gu0o00,

the error is caused by the fact that at the moment it is possible to attach only passing the PID of the process (that is a number). 

I will change soon this functionality in order to let the user to attach also by passing the application name.

Federico

**Comment by federicodotta** [comment] 2021-03-15 08:59
HI @firekeeper123 and @gu0o00,

from commmit 68ad80a61960a877e1a70764b1d6bf5c3dd59719 you can also attach by process name. You can find a compiled version of Brida that inlcudes this change here: https://github.com/federicodotta/Brida/releases/tag/v0.5pre

Pay attention that the "process name" that you have to use with the "Attach" functionality can be different from the "package id" that you can use with the "Spawn" functionality. As an example, is iOS are different and you can get the process name using frida-ps tool.

Please let me know if your issue is solved.

Federico

**Comment by federicodotta** [comment] 2021-05-03 12:44
HI!

I close the issue because it should be solved right now. Please open a new issue if you have still problems.

Federico

**Closed by federicodotta** 2021-05-03 12:44 UTC
Labels: enhancement
