### ISSUE TITLE
Timeout Exception when spawning an Application on iOS11

### ISSUE THREAD

**Issue by martinnnnnnn** [federicodotta/Brida#15] opened 2018-06-21 13:00 UTC
Spawning and attaching to an Application raised a Timeout Exception for me on iOS11 and Darwin (I believe the actual problem is caused by Frida, not Brida).
As a workaround I allowed Brida to attach to an already running App and manually started the target App before clicking "Spawn application" in Burp. 
I modified bridaServicePyro.py by adding the function get_applications, taken from https://github.com/AloneMonkey/frida-ios-dump,  and changing spawn_application. After manually building the project, it worked for me.

```
    def get_applications(self):
        try:
            applications = self.device.enumerate_applications()
        except Exception as e:
            print(('Failed to enumerate applications: %s' % e))
            return

        return applications

    def spawn_application(self,application_id,frida_script,remote):

        self.application_id = application_id
        self.frida_script = frida_script

        if remote == True:
            self.device = frida.get_remote_device()
        else:
            self.device = frida.get_usb_device()

        self.pid = ''
        for application in self.get_applications():
            if application_id == application.identifier or application_id == application.name:
                self.pid = application.pid

        try:
            if not self.pid:
                self.pid = self.device.spawn([bundle_identifier])
                self.device.resume(self.pid)
            else:
                self.session = self.device.attach(self.pid)
        except Exception as e:
            pass


        #self.pid = self.device.spawn([self.application_id])

        #self.session = self.device.attach(self.pid)

        with codecs.open(self.frida_script, 'r', 'utf-8') as f:
            source = f.read()

        self.script = self.session.create_script(source)
        self.script.load()

        #self.device.resume(self.pid)

        return
```

**Comment by federicodotta** [comment] 2018-07-05 10:16
Hi martinnnnnnn! I have not already tried Brida with iOS 11. When I will have a device with that version of iOS I will try! Thank you for your workaround!

**Comment by lukaszbobrek** [comment] 2018-07-06 07:51
@martinnnnnnn can you please share release with your build? 
I am facing exactly the same problem on Android, which only proves that the issue is with frida itself.

**Comment by oschvr** [comment] 2019-12-10 16:43
Hey @martinnnnnnn, your solution works. Thank you.

@lukaszbobrek just download the latest release, modify the python script in `Brida-0.3/res/bridaServicePyro.py` and then compile using `mvn package`

Or... here's the binary and the binary with dependencies:

(I had to fork it and version it. However note that it is NOT an official release from @federicodotta )
https://github.com/oschvr/Brida/releases/tag/v0.3.1

**Comment by federicodotta** [comment] 2020-03-07 09:11
Hi! Thank you for the workaround! Currently I didn't experienced a similar issue.

In order to avoid similar issues, I added the "Attach" functionality to the new version of Brida, that executes the attach instead of the spawn and takes a PID as input. I will release this version on June for HackInParis 2020.

**Comment by federicodotta** [comment] 2020-04-15 09:16
Version 0.4 of Brida released yesterday allows to choose between attach and spawn. I close this issue. Please try the new version and re-open the issue if you continue to experience the problem.

**Closed by federicodotta** 2020-04-15 09:16 UTC
Labels: enhancement
