### ISSUE TITLE
Hook Bug

### ISSUE THREAD

**Issue by Brubs-Rocks** [federicodotta/Brida#86] opened 2021-08-23 15:29 UTC
Hi!

I'm doing the hooks to encrypt and decrypt the data of the requests / responses and is operating normally.
But I'm in a scenario where in a given application flow, a http response is quite big, for example "**317990 - Length**", so I noticed that the decrypt in this response doesn't work.
II think this is because of the size of the response. Can you tell if there is a way to get around this type of situation? 

**Log returned:**

`Error when calling Frida exported function decryptedbase64 through Pyro in custom plugin java.util.concurrent.TimeoutException java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) burp.BurpExtender.executePyroCall(BurpExtender.java:2830) burp.CustomPlugin.callFrida(CustomPlugin.java:259) burp.BridaMessageEditorPlugin$BridaMessageEditorPluginInner.setMessage(BridaMessageEditorPlugin.java:183) burp.h0d.a(Unknown Source) burp.bba.b(Unknown Source) burp.f2k.a(Unknown Source) burp.gmy.b(Unknown Source) burp.gmy.a(Unknown Source) burp.hro.a(Unknown Source) burp.hro.b(Unknown Source) burp.hr8.e(Unknown Source) burp.i61.mouseReleased(Unknown Source) java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298) java.desktop/java.awt.Component.processMouseEvent(Component.java:6614) java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) java.desktop/java.awt.Component.processEvent(Component.java:6379) java.desktop/java.awt.Container.processEvent(Container.java:2263) java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) java.desktop/java.awt.Component.dispatchEvent(Component.java:4822) java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919) java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548) java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769) java.desktop/java.awt.Component.dispatchEvent(Component.java:4822) java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) `

**Burp Version:** 2021.8.1

**Comment by federicodotta** [comment] 2021-08-24 13:04
Hi @Brubs-Rocks,

The exception is caused by a specific Java instruction that I inserted in order to prevent Burp Suite freezes caused by Frida issues. In detail, around any Frida call there is a Java instruction that kills the Frida call if it did not returns by 30 seconds. Probably your large requests require more time to compute and consequently you get the exception.

In order to fix your issue you can change line 2825 of BurpExtender.java file, changing 30 seconds:

`future.get(30, TimeUnit.SECONDS);`

to another value like 300 seconds (5 minutes):

`future.get(300, TimeUnit.SECONDS);`

After changing that line you have to recompile Brida. You can refer to [Brida Wiki](https://github.com/federicodotta/Brida/wiki/Build) for the Maven compilation.

Please let me know if this workaround solves your issue.

Federico

**Comment by federicodotta** [comment] 2021-11-01 18:28
Hi @Brubs-Rocks,

I close the issue. Please open another one if you need more help.

Federico

**Closed by federicodotta** 2021-11-01 18:28 UTC
